version: "3.7"
services:
    backend:
        build:
            context: .
            dockerfile: back_end.Dockerfile
            target: production
            args:
                - DANIEL_SCRIPT_DIR=/app/back_end/scripts
                - DANIEL_DB_DIR=/db
                - DANIEL_USERDAT_DIR=/userdat
        image: bioinformaticsleibnizhki/daniel_backend
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "10"
                    memory: "20G"
                reservations:
                    cpus: "10"
                    memory: "5G"
        ports:
            - "9001:22"
        volumes:
            - ${DANIEL_USERDAT_DIR}:/userdat
            - ${DANIEL_DB_DIR}:/db:ro
            - ${DANIEL_DIR}/repo:/app
        environment:
            - DANIEL_SCRIPT_DIR=/app/back_end/scripts
            - DANIEL_DB_DIR=/db
            - DANIEL_USERDAT_DIR=/userdat
    frontend:
        build:
            context: .
            dockerfile: front_end.Dockerfile
            target: production
        image: bioinformaticsleibnizhki/daniel_frontend
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "2"
                    memory: "5G"
                reservations:
                    cpus: "2"
                    memory: "5G"
        ports:
            - "3838:3838"
            - "8888:8888"
        volumes:
            - ${DANIEL_DIR}/repo/front_end:/srv/shiny-server/latest
            - ${DANIEL_USERDAT_DIR}:/userdat
            - ${DANIEL_DB_DIR}:/db:ro
        environment:
            - DANIEL_DB_DIR=/db
            - DANIEL_USERDAT_DIR=/userdat
